services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./config/.env
    environment:
      - AKTYWUJ_KOMUNIKATOR=${AKTYWUJ_KOMUNIKATOR}
      - RPI=${RPI}

  gpio-worker:
    privileged: true
    devices:
      - "/dev/gpiochip0:/dev/gpiochip0"
    build:
      context: .
      dockerfile: Dockerfile.gpio
    volumes:
      - .:/usr/src/app/
    ports:
      - "9823:9823"
    depends_on:
      - db
    env_file:
      - ./config/.env
    environment:
      - RPI=${RPI}
      
  db:
    image: postgres:16.4-bullseye
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env.db

volumes:
  postgres_data: